server:
  port: ${SERVER_PORT:8080}
spring:
  application.name: ${APPLICATION_NAME:spring-security-keycloak}
keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: testing realm
  resource: my_new_client
  public-client: true

#server:
#  port: 8082
#
#keycloak:
#  auth-server-url: http://localhost:8081/auth
#  realm: "my_realm"
#  resource: "my_client"
#  bearer-only: true
#  security-constraints:
#    - authRoles:
#        - uma_authorization
#      securityCollections:
#        - patterns:
#            - /api/*